#
#  generated by Claude
#
from i2cpy import I2C
from PIL import Image, ImageDraw, ImageFont
import time
import os

SH1106_ADDR = 0x3C
SH1106_COMMAND = 0x00
SH1106_DATA = 0x40
DISPLAY_WIDTH = 128
DISPLAY_HEIGHT = 64

# 初期化コマンド
SH1106_INIT_COMMANDS = [
    0xAE,       # Display OFF
    0xD5, 0x80, # Set display clock divide ratio/oscillator frequency
    0xA8, 0x3F, # Set multiplex ratio (1 to 64)
    0xD3, 0x00, # Set display offset
    0x40,       # Set display start line
    0x8D, 0x14, # Charge pump setting
    0x20, 0x00, # Set memory addressing mode
    0xA1,       # Set segment re-map (A0/A1)
    0xC8,       # Set COM output scan direction
    0xDA, 0x12, # Set COM pins hardware configuration
    0x81, 0x80, # Set contrast control
    0xD9, 0xF1, # Set pre-charge period
    0xDB, 0x30, # Set VCOMH deselect level
    0xA4,       # Entire display ON
    0xA6,       # Set normal display
    0xAF        # Display ON
]

class SH1106Display:
    def __init__(self, i2c_freq=20000):
        self.i2c = I2C(driver="ch341", freq=i2c_freq)
        self.buffer = [[0 for _ in range(DISPLAY_WIDTH)] for _ in range(DISPLAY_HEIGHT)]
        
    def init_display(self):
        """ディスプレイを初期化"""
        print("Initializing SH1106 display...")
        for cmd in SH1106_INIT_COMMANDS:
            #print(f"Sending command: 0x{cmd:02X}")
            self.i2c.writeto(SH1106_ADDR, bytes([SH1106_COMMAND, cmd]))
            time.sleep(0.01)
        time.sleep(0.5)
    
    def clear_display(self):
        """ディスプレイをクリア"""
        print("Clearing display...")
        # バッファをクリア
        self.buffer = [[0 for _ in range(DISPLAY_WIDTH)] for _ in range(DISPLAY_HEIGHT)]
        
        # ハードウェアをクリア
        for page in range(8):
            self.i2c.writeto(SH1106_ADDR, bytes([SH1106_COMMAND, 0xB0 + page]))
            self.i2c.writeto(SH1106_ADDR, bytes([SH1106_COMMAND, 0x02]))
            self.i2c.writeto(SH1106_ADDR, bytes([SH1106_COMMAND, 0x10]))
            
            # 128バイトのゼロデータを一度に送信
            clear_data = bytes([SH1106_DATA]) + bytes([0x00] * DISPLAY_WIDTH)
            self.i2c.writeto(SH1106_ADDR, clear_data)
    
    def set_pixel(self, x, y, value):
        """ピクセルをバッファに設定"""
        if 0 <= x < DISPLAY_WIDTH and 0 <= y < DISPLAY_HEIGHT:
            self.buffer[y][x] = 1 if value else 0
    
    def draw_bitmap(self, bitmap, x_offset=0, y_offset=0):
        """ビットマップをバッファに描画"""
        height, width = len(bitmap), len(bitmap[0])
        for y in range(height):
            for x in range(width):
                if bitmap[y][x]:
                    self.set_pixel(x + x_offset, y + y_offset, 1)
    def safe_update_display(self):
        """より安全なディスプレイ更新"""
        for page in range(8):
            # 各ページごとにアドレスを再設定
            self.i2c.writeto(SH1106_ADDR, bytes([SH1106_COMMAND, 0xB0 + page]))
            self.i2c.writeto(SH1106_ADDR, bytes([SH1106_COMMAND, 0x02]))
            self.i2c.writeto(SH1106_ADDR, bytes([SH1106_COMMAND, 0x10]))
            
            # 16バイトずつ送信（メモリ制限がある場合）
            for chunk_start in range(0, DISPLAY_WIDTH, 16):
                chunk_end = min(chunk_start + 16, DISPLAY_WIDTH)
                chunk_data = []
                
                for col in range(chunk_start, chunk_end):
                    byte_val = 0
                    for bit in range(8):
                        row = page * 8 + bit
                        if row < DISPLAY_HEIGHT and self.buffer[row][col]:
                            byte_val |= (1 << bit)
                    chunk_data.append(byte_val)
                
                self.i2c.writeto(SH1106_ADDR, bytes([SH1106_DATA]) + bytes(chunk_data))
                time.sleep(0.001)  # 短い待機時間
            
    def update_display(self):
        """バッファの内容をディスプレイに送信"""
        print("Updating display...")
        for page in range(8):
            # ページアドレスを設定
            self.i2c.writeto(SH1106_ADDR, bytes([SH1106_COMMAND, 0xB0 + page]))
            # 列アドレスを設定（SH1106の2列オフセットあり）
            self.i2c.writeto(SH1106_ADDR, bytes([SH1106_COMMAND, 0x02]))  # 下位アドレス
            self.i2c.writeto(SH1106_ADDR, bytes([SH1106_COMMAND, 0x10]))  # 上位アドレス
            
            # 1ページ分のデータを準備（128バイト）
            page_data = []
            for col in range(DISPLAY_WIDTH):
                byte_val = 0
                for bit in range(8):
                    row = page * 8 + bit
                    if row < DISPLAY_HEIGHT and self.buffer[row][col]:
                        byte_val |= (1 << bit)
                page_data.append(byte_val)
            
            # 128バイトを一度に送信
            self.i2c.writeto(SH1106_ADDR, bytes([SH1106_DATA]) + bytes(page_data))

def get_windows_font(font_name="arial.ttf", size=12):
    """Windowsフォントを読み込み"""
    # Windowsフォントディレクトリ
    font_dirs = [
        "C:/Windows/Fonts/",
        "C:/Windows/System32/Fonts/"
    ]
    
    # よく使われるフォントファイル名
    font_files = {
        "arial": "arial.ttf",
        "times": "times.ttf", 
        "courier": "cour.ttf",
        "comic": "comic.ttf",
        "georgia": "georgia.ttf",
        "tahoma": "tahoma.ttf",
        "verdana": "verdana.ttf",
        "calibri": "calibri.ttf",
        "meiryo": "meiryo.ttc",  # 日本語フォント
        "msgothic": "msgothic.ttc"  # 日本語フォント
    }
    
    # フォント名から適切なファイル名を取得
    if font_name.lower() in font_files:
        font_file = font_files[font_name.lower()]
    else:
        font_file = font_name
    
    # フォントファイルを検索
    for font_dir in font_dirs:
        font_path = os.path.join(font_dir, font_file)
        if os.path.exists(font_path):
            try:
                return ImageFont.truetype(font_path, size)
            except Exception as e:
                print(f"フォント読み込みエラー: {e}")
                continue
    
    # デフォルトフォントを使用
    print(f"フォント '{font_name}' が見つかりません。デフォルトフォントを使用します。")
    return ImageFont.load_default()

def text_to_bitmap(text, font_name="arial", font_size=12):
    """テキストをビットマップに変換"""
    font = get_windows_font(font_name, font_size)
    
    # テキストのサイズを計算
    temp_img = Image.new('1', (1, 1))
    temp_draw = ImageDraw.Draw(temp_img)
    bbox = temp_draw.textbbox((0, 0), text, font=font)
    text_width = bbox[2] - bbox[0]
    text_height = bbox[3] - bbox[1]
    
    # マージンを追加してテキストの切れを防ぐ
    margin = 2
    img_width = text_width + margin * 2
    img_height = text_height + margin * 2
    
    # テキストを描画
    img = Image.new('1', (img_width, img_height), 0)
    draw = ImageDraw.Draw(img)
    draw.text((margin, margin), text, font=font, fill=1)
    
    # ビットマップ配列に変換
    bitmap = []
    for y in range(img_height):
        row = []
        for x in range(img_width):
            pixel = img.getpixel((x, y))
            row.append(pixel)
        bitmap.append(row)
    
    return bitmap

def display_text_with_font(display, text, font_name="arial", font_size=12, x=0, y=0):
    """指定されたフォントでテキストを表示"""
    print(f"Creating bitmap for '{text}' using {font_name} font, size {font_size}")
    bitmap = text_to_bitmap(text, font_name, font_size)
    
    print(f"Bitmap size: {len(bitmap[0])}x{len(bitmap)} pixels")
    display.draw_bitmap(bitmap, x, y)
    display.safe_update_display()

# メイン処理
if __name__ == "__main__":
    # ディスプレイオブジェクト作成
    display = SH1106Display()
    
    # 初期化
    display.init_display()
    display.clear_display()
    
    # 利用可能なフォントの例
    available_fonts = ["arial", "times", "courier", "comic", "tahoma", "verdana", "calibri"]
    
    # "Hello World."を表示（改善されたレイアウト）
    display.clear_display()
    
    texts_to_display = [
        ("Hello World!", "courier", 12, 5, 5),
        ("Font Test", "courier", 12, 5, 20),
        ("SH1106", "courier", 12, 20, 35),
        ("Display OK", "courier", 12, 10, 50)
    ]
    
    for text, font_name, font_size, x, y in texts_to_display:
        try:
            print(f"Displaying: {text} at ({x},{y})")
            display_text_with_font(display, text, font_name, font_size, x, y)
            time.sleep(0.5)  # 各テキスト表示後に少し待機
        except Exception as e:
            print(f"Error displaying '{text}': {e}")
    
    print("Text display completed!")
